
import __ASTRO_IMAGE_IMPORT_QUchz from "Attachments/Pasted image 20250222091010.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FEvery+field+becomes+computational.md";
import __ASTRO_IMAGE_IMPORT_Z265aFn from "Attachments/Pasted image 20250222091010.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FComputational+and+AI+everything.md";
import __ASTRO_IMAGE_IMPORT_ZppvBE from "Attachments/IMG_5767.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FProductCon+2025.md";
import __ASTRO_IMAGE_IMPORT_68nds from "Attachments/Pasted image 20250214164749.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FTransfering+writing+styles+with+AI.md";
import __ASTRO_IMAGE_IMPORT_20e20K from "Attachments/shreyas-14-02-2025 at 16.50.51.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FTransfering+writing+styles+with+AI.md";
import __ASTRO_IMAGE_IMPORT_11JNVp from "Attachments/shreyas-14-02-2025 at 16.54.28.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FTransfering+writing+styles+with+AI.md";
import __ASTRO_IMAGE_IMPORT_JNhid from "Attachments/shreyas-14-02-2025 at 16.55.58.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FTransfering+writing+styles+with+AI.md";
import __ASTRO_IMAGE_IMPORT_Z2jW5a from "Attachments/shreyas-15-02-2025 at 09.02.49.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FUnderstanding+codebases+without+using+code.md";
import __ASTRO_IMAGE_IMPORT_eirBD from "Attachments/shreyas-15-02-2025 at 08.57.21.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FUnderstanding+codebases+without+using+code.md";
import __ASTRO_IMAGE_IMPORT_Z10OmSr from "Attachments/shreyas-15-02-2025 at 08.57.28.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FUnderstanding+codebases+without+using+code.md";
import __ASTRO_IMAGE_IMPORT_Z2tKv9q from "Attachments/shreyas-15-02-2025 at 08.57.09.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FUnderstanding+codebases+without+using+code.md";
import __ASTRO_IMAGE_IMPORT_Z1lDat9 from "Attachments/IMG_5786.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FVirtual+bookshelves.md";
import __ASTRO_IMAGE_IMPORT_4Aur9 from "Attachments/IMG_5787.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FVirtual+bookshelves.md";
import __ASTRO_IMAGE_IMPORT_1uPamr from "Attachments/IMG_5788.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FVirtual+bookshelves.md";
export default new Map([["Attachments/Pasted image 20250222091010.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FEvery+field+becomes+computational.md", __ASTRO_IMAGE_IMPORT_QUchz], ["Attachments/Pasted image 20250222091010.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FComputational+and+AI+everything.md", __ASTRO_IMAGE_IMPORT_Z265aFn], ["Attachments/IMG_5767.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FProductCon+2025.md", __ASTRO_IMAGE_IMPORT_ZppvBE], ["Attachments/Pasted image 20250214164749.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FTransfering+writing+styles+with+AI.md", __ASTRO_IMAGE_IMPORT_68nds], ["Attachments/shreyas-14-02-2025 at 16.50.51.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FTransfering+writing+styles+with+AI.md", __ASTRO_IMAGE_IMPORT_20e20K], ["Attachments/shreyas-14-02-2025 at 16.54.28.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FTransfering+writing+styles+with+AI.md", __ASTRO_IMAGE_IMPORT_11JNVp], ["Attachments/shreyas-14-02-2025 at 16.55.58.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FTransfering+writing+styles+with+AI.md", __ASTRO_IMAGE_IMPORT_JNhid], ["Attachments/shreyas-15-02-2025 at 09.02.49.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FUnderstanding+codebases+without+using+code.md", __ASTRO_IMAGE_IMPORT_Z2jW5a], ["Attachments/shreyas-15-02-2025 at 08.57.21.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FUnderstanding+codebases+without+using+code.md", __ASTRO_IMAGE_IMPORT_eirBD], ["Attachments/shreyas-15-02-2025 at 08.57.28.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FUnderstanding+codebases+without+using+code.md", __ASTRO_IMAGE_IMPORT_Z10OmSr], ["Attachments/shreyas-15-02-2025 at 08.57.09.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FUnderstanding+codebases+without+using+code.md", __ASTRO_IMAGE_IMPORT_Z2tKv9q], ["Attachments/IMG_5786.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FVirtual+bookshelves.md", __ASTRO_IMAGE_IMPORT_Z1lDat9], ["Attachments/IMG_5787.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FVirtual+bookshelves.md", __ASTRO_IMAGE_IMPORT_4Aur9], ["Attachments/IMG_5788.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FVirtual+bookshelves.md", __ASTRO_IMAGE_IMPORT_1uPamr]]);
		