import * as vscode from 'vscode';
import * as path from 'path';
import { DocumentationSession, PromptEntry, FileChange } from './documentationSession';

export class MarkdownExporter {
    constructor(private session: DocumentationSession) {}

    async exportToMarkdown(): Promise<void> {
        const sessionData = this.session.getSessionData();
        const markdown = this.generateMarkdown(sessionData);
        
        const defaultUri = this.getDefaultExportPath();
        const uri = await vscode.window.showSaveDialog({
            defaultUri,
            filters: {
                'Markdown': ['md'],
                'All Files': ['*']
            },
            saveLabel: 'Export Documentation'
        });

        if (uri) {
            await vscode.workspace.fs.writeFile(uri, Buffer.from(markdown, 'utf8'));
            vscode.window.showInformationMessage(`Documentation exported to ${uri.fsPath} 🎉`);
            
            // Optionally open the exported file
            const openChoice = await vscode.window.showInformationMessage(
                'Documentation exported successfully!', 
                'Open File'
            );
            
            if (openChoice === 'Open File') {
                await vscode.window.showTextDocument(uri);
            }
        }
    }

    private generateMarkdown(sessionData: any): string {
        const { startTime, prompts, fileChanges, duration } = sessionData;
        const formattedDuration = this.formatDuration(duration);
        
        let markdown = '';
        
        // Header
        markdown += `# AI-Assisted Development Session\n\n`;
        markdown += `**Session Date:** ${startTime.toLocaleDateString()}\n`;
        markdown += `**Duration:** ${formattedDuration}\n`;
        markdown += `**Prompts:** ${prompts.length}\n`;
        markdown += `**File Changes:** ${fileChanges.length}\n\n`;
        
        // Introduction
        markdown += `## Overview\n\n`;
        markdown += `This document captures an AI-assisted development session, showing the iterative process of building features through prompts and code changes. The session demonstrates how AI can help accelerate development by understanding requirements and generating focused code modifications.\n\n`;
        
        // Table of Contents
        markdown += `## Table of Contents\n\n`;
        prompts.forEach((prompt: PromptEntry, index: number) => {
            const title = this.extractPromptTitle(prompt.prompt);
            markdown += `${index + 1}. [${title}](#${this.slugify(title)})\n`;
        });
        markdown += `\n`;
        
        // Development Timeline
        markdown += `## Development Timeline\n\n`;
        
        const timeline = this.createTimeline(prompts, fileChanges);
        
        timeline.forEach((item, index) => {
            if (item.type === 'prompt') {
                const prompt = item.data as PromptEntry;
                const title = this.extractPromptTitle(prompt.prompt);
                
                markdown += `### ${index + 1}. ${title}\n\n`;
                markdown += `**Time:** ${prompt.timestamp.toLocaleTimeString()}\n\n`;
                
                // Format the prompt nicely
                const formattedPrompt = this.formatPrompt(prompt.prompt);
                markdown += `**Request:**\n`;
                markdown += `> ${formattedPrompt}\n\n`;
                
                // Show related file changes
                const relatedChanges = this.getRelatedFileChanges(prompt, fileChanges);
                if (relatedChanges.length > 0) {
                    markdown += `**Code Changes:**\n\n`;
                    relatedChanges.forEach(change => {
                        markdown += this.formatFileChange(change);
                    });
                }
                
                markdown += `---\n\n`;
            }
        });
        
        // Summary
        markdown += `## Session Summary\n\n`;
        markdown += `This session demonstrated AI-assisted development across ${fileChanges.length} file changes in ${formattedDuration}. `;
        markdown += `The development process was guided by ${prompts.length} prompts, each resulting in targeted code modifications.\n\n`;
        
        // File Changes Summary
        const fileStats = this.generateFileStats(fileChanges);
        markdown += `### Files Modified\n\n`;
        Object.entries(fileStats).forEach(([fileName, stats]: [string, any]) => {
            markdown += `- **${fileName}**: ${stats.changes} change${stats.changes > 1 ? 's' : ''}\n`;
        });
        
        markdown += `\n---\n\n`;
        markdown += `*Generated by AI Documentation Exporter at ${new Date().toLocaleString()}*\n`;
        
        return markdown;
    }

    private createTimeline(prompts: PromptEntry[], fileChanges: FileChange[]): Array<{type: 'prompt' | 'change', data: PromptEntry | FileChange, timestamp: Date}> {
        const timeline: Array<{type: 'prompt' | 'change', data: PromptEntry | FileChange, timestamp: Date}> = [];
        
        prompts.forEach(prompt => {
            timeline.push({ type: 'prompt', data: prompt, timestamp: prompt.timestamp });
        });
        
        fileChanges.forEach(change => {
            timeline.push({ type: 'change', data: change, timestamp: change.timestamp });
        });
        
        return timeline.sort((a, b) => a.timestamp.getTime() - b.timestamp.getTime());
    }

    private getRelatedFileChanges(prompt: PromptEntry, fileChanges: FileChange[]): FileChange[] {
        // Find file changes that occurred within 2 minutes after the prompt
        const promptTime = prompt.timestamp.getTime();
        const timeWindow = 2 * 60 * 1000; // 2 minutes
        
        return fileChanges.filter(change => {
            const changeTime = change.timestamp.getTime();
            return changeTime >= promptTime && changeTime <= promptTime + timeWindow;
        });
    }

    private formatFileChange(change: FileChange): string {
        let markdown = `#### ${this.getChangeIcon(change.changeType)} \`${change.filePath}\`\n\n`;
        
        if (change.diff) {
            // Clean up and format the diff
            const cleanDiff = this.cleanDiff(change.diff);
            markdown += `\`\`\`diff\n${cleanDiff}\n\`\`\`\n\n`;
        }
        
        return markdown;
    }

    private cleanDiff(diff: string): string {
        // Remove excessive context and make diff more readable
        const lines = diff.split('\n');
        const relevantLines = lines.filter(line => {
            // Keep diff headers and actual changes
            return line.startsWith('@@') || 
                   line.startsWith('+') || 
                   line.startsWith('-') ||
                   line.includes('(new file)') ||
                   line.includes('(deleted file)') ||
                   line.includes('more lines');
        });
        
        // Limit to most important changes
        if (relevantLines.length > 20) {
            const important = relevantLines.slice(0, 15);
            const remaining = relevantLines.length - 15;
            important.push(`... (${remaining} more lines)`);
            return important.join('\n');
        }
        
        return relevantLines.join('\n');
    }

    private getChangeIcon(changeType: string): string {
        switch (changeType) {
            case 'created': return '🆕';
            case 'modified': return '✏️';
            case 'deleted': return '🗑️';
            default: return '📝';
        }
    }

    private extractPromptTitle(prompt: string): string {
        // Extract a meaningful title from the prompt
        const sentences = prompt.split(/[.!?]/);
        const firstSentence = sentences[0].trim();
        
        // Clean up and limit length
        let title = firstSentence.length > 60 ? 
                   firstSentence.substring(0, 60) + '...' : 
                   firstSentence;
        
        // Remove common prefixes
        title = title.replace(/^(I want to|I need to|Can you|Please|Let's|Could you)/i, '').trim();
        
        // Capitalize first letter
        title = title.charAt(0).toUpperCase() + title.slice(1);
        
        return title || 'Development Task';
    }

    private formatPrompt(prompt: string): string {
        // Clean up and format the prompt text
        return prompt
            .replace(/\n+/g, ' ') // Replace line breaks with spaces
            .replace(/\s+/g, ' ') // Normalize whitespace
            .trim();
    }

    private slugify(text: string): string {
        return text
            .toLowerCase()
            .replace(/[^\w\s-]/g, '') // Remove special chars
            .replace(/\s+/g, '-') // Replace spaces with hyphens
            .replace(/-+/g, '-') // Remove multiple hyphens
            .replace(/^-|-$/g, ''); // Remove leading/trailing hyphens
    }

    private formatDuration(milliseconds: number): string {
        const minutes = Math.floor(milliseconds / 60000);
        const seconds = Math.floor((milliseconds % 60000) / 1000);
        
        if (minutes > 0) {
            return `${minutes}m ${seconds}s`;
        }
        return `${seconds}s`;
    }

    private generateFileStats(fileChanges: FileChange[]): Record<string, {changes: number}> {
        const stats: Record<string, {changes: number}> = {};
        
        fileChanges.forEach(change => {
            const fileName = path.basename(change.filePath);
            if (!stats[fileName]) {
                stats[fileName] = { changes: 0 };
            }
            stats[fileName].changes++;
        });
        
        return stats;
    }

    private getDefaultExportPath(): vscode.Uri {
        const workspaceFolders = vscode.workspace.workspaceFolders;
        const defaultName = `ai-docs-session-${new Date().toISOString().split('T')[0]}.md`;
        
        if (workspaceFolders && workspaceFolders.length > 0) {
            return vscode.Uri.joinPath(workspaceFolders[0].uri, defaultName);
        }
        
        return vscode.Uri.file(defaultName);
    }
} 